### ISSUE TITLE
Might need another updated for `purs` 0.11.6?

### ISSUE THREAD

**Issue by metaleap** [benjamin-hodgson/purescript-bound#3]
using `purs` current `master` branch (prints `--version` as `0.11.6 dev build`), attempting to `pulp build` build a project with `purescript-bound` (got version 0.5.0 from Pursuit) in the deps results in:

    * Building project in ~/c/ps/test-pscorefn-src
    Compiling Bound
    Error found:
    at bower_components/purescript-bound/src/Bound.purs line 87, column 8 - line 87, column 74
    
      Cannot derive a type class instance for
                                      
        Data.Generic.Generic (Var b a)
                                      
      since instances of this type class are not derivable.

**Comment by benjamin-hodgson** [comment]
I'd be happy to accept a pull request to fix this.

**Comment by benjamin-hodgson** [comment]
https://github.com/benjamin-hodgson/purescript-bound/pull/4
